server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///mybatis?serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: service-provider # 为服务名称
mybatis:
  type-aliases-package: com.ntuzy.service.pojo

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka


