
server:
  port: 10010
spring:
  application:
    name: ntuzy-zuul
zuul:
  routes:
    service-provider: /user/**
    # ×¢²á·þÎñµÄid
    service-consumer: /consumer/**
#  prefix: /api
      # path: /service-provider/**
      # url: http://localhost:8080 # http://localhost:8080/user/28 -> http://localhost:10010/service-provider/user/28
      # serviceId: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

